### ISSUE TITLE
Hardcoded value in UpdateGUI prevents showing long strings.

### ISSUE THREAD

**Issue by SmugZombie** [JeffReeves/Sunny#3]
`
UpdateGUI(this) {

    this.sectionWidth := 320
    fontSize := 10

    startPos := 1
    endPos := this.sectionWidth / fontSize

    Loop, % this.clipboards.Length() {

        trimmedClipboard := this.clipboards[A_Index]
        trimmedClipboard := SubStr(trimmedClipboard, startPos, endPos)

        StringReplace, trimmedClipboard, trimmedClipboard, `r`n,,
        StringReplace, trimmedClipboard, trimmedClipboard, `n,,

        GuiControl, -redraw, % "[" A_Index "]"
        GuiControl,, % "[" A_Index "]", % "[" A_Index "] " trimmedClipboard 
        GuiControl, +redraw, % "[" A_Index "]"
    }
    
    return
}
`

The "this.sectionWidth" re-definition breaks long strings, at least when using 9 clips, removing the definition fixes the issue.

**Comment by JeffReeves** [comment]
Thank you for bringing this to my attention, and for providing a fix for it!

I was able to duplicate the issue when copying a long string with no break characters (spaces, tabs, newlines, etc.); as well as duplicate the fix working when line 207 is removed:

`this.sectionWidth := 320`

Appreciate the help!
